### ISSUE TITLE
Error when using breeze bridge in angular 4

### ISSUE THREAD

**Issue by bancroftway** [Breeze/breeze.bridge.angular#16]
I created a new Angular 4 app using the angular cli, and when I imported and added the BreezeBridgeAngular2Module, I get an exception in console:
`Uncaught Error: Unexpected value 'BreezeBridgeAngular2Module' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:63598:34)
    at http://localhost:4200/vendor.bundle.js:77282:44
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:77265:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:88588:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:88561:36)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:88490:37)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:94231:25)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:94217:21)
    at Object.../../../../../src/main.ts (http://localhost:4200/main.bundle.js:206:124)`

My app.module.ts is:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from "@angular/forms";
import { HttpModule } from "@angular/http";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { MdButtonModule, MdCardModule, MdMenuModule, MdToolbarModule, MdIconModule } from '@angular/material';
import { BreezeBridgeAngular2Module } from 'breeze-bridge-angular2'

import { AppComponent } from './app.component';
import { DatabaseServiceService } from 'app/database-service.service';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
      BrowserModule,
      BrowserAnimationsModule,
      FormsModule,
      HttpModule,
      MdButtonModule, MdCardModule, MdMenuModule, MdToolbarModule, MdIconModule,
      BreezeBridgeAngular2Module
  ],
  providers: [DatabaseServiceService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Also, the angular cli gives a compile warning:
```
WARNING in ./~/breeze-bridge-angular2/~/@angular/http/src/backends/xhr_backend.js
206:41-69 "export '__platform_browser_private__' was not found in '@angular/platform-browser'
webpack: Compiled with warnings.
```

**Comment by marcelgood** [comment]
You are using the wrong package. The latest package is called `breeze-bridge-angular`. See the README https://github.com/Breeze/breeze.bridge.angular/blob/master/README.md
